### ISSUE TITLE
Nuget?

### ISSUE THREAD

**Issue by vanerleo** [chrislove/Hangfire.MySql#1]
Any chance of creating this as a nuget package?

**Comment by S3NS4Ti0N** [comment]
+1

**Comment by chrislove** [comment]
Yes definitely. As soon as I have it doing the "bare minimum" to be useful I'll make a nuget package. I'm hoping to be at that stage sometime in the next week.

**Comment by vanerleo** [comment]
Just a heads up, these seems to be a performance issues .. when using the lib .. Mysql queue Depth spikes dramatically  & IIS worker process cpu spikes to 80% or so ... which leads me to believe that the mysql server gets flooded with IO and becomes the bottleneck hence increased IIS cpu

as soon as i've changed to HangfireMemory .. all became good

**Comment by chrislove** [comment]
Thanks for the heads up :)  I haven't looked at performance so it really is helpful to know that's on the horizon. I'll raise a separate issue for it so you can tell when I think it's fixed. And I'll get that nuget package sorted out - I didn't realise anyone was actually running it!

**Comment by vanerleo** [comment]
Hey chrislove, any progress on this?

**Comment by DanubeRS** [comment]
I'll jump on it either tonight or over the weekend. I'll create the feed, and pass the reins over to Chris shortly.

**Comment by JiaJian** [comment]
Would love to have it too! Any updates on this?

**Comment by chrislove** [comment]
.nuspec file and package built and published at https://www.nuget.org/packages/Hangfire.MySql
