### ISSUE TITLE
.Net version

### ISSUE THREAD

**Issue by mwillebrands** [chrislove/Hangfire.MySql#11]
Any way you can downgrade the package to use the same version of .NET as hangfire?

**Comment by chrislove** [comment]
That makes sense. Working on it now.

**Comment by chrislove** [comment]
Downgrade project to .NET 4.5 to match Hangfire 8b9d81651eb96d9a4c560cb2c6202c2de150369d

**Comment by mwillebrands** [comment]
Great, thanks!
