### ISSUE TITLE
Tables are not automatically created?

### ISSUE THREAD

**Issue by mwillebrands** [chrislove/Hangfire.MySql#4]
When starting Hangfire with the Mysql Connector i recieve the following error:
"Table 'databasename.server' doesn't exist".

Aren't the tables created automaticly?

**Comment by chrislove** [comment]
That EnsureDatabase method you wrote seems to solve the problem nicely. I've merged your commits into develop. When running it I realised we'll have to supply a value for DataType on the properties that need to map to MySql Text columns so if fixed that.

Apologies for not responding to your Pull Request more quickly.. stupid day job.

**Comment by mwillebrands** [comment]
No worries, i have closed the pull request   because it does not create
constraints yet. Don't know if we should include them.

I've got a problem with the MySQL storage because it uses up all the
connections in the pool and does not release them. Havent checked yet if
that only occurs in my version.
Op 1 dec. 2015 18:36 schreef "Chris Love" <notifications@github.com>:

**Comment by chrislove** [comment]
I guess right now it's more helpful that it creates the tables and runs "out-of-the-box". But yes we'll have to figure out what to do about the constraints at some stage. 

I'm trying to figure out why the connection pool isn't being used properly. I'm adding some tracing code in to try and figure out what circumstances lead to the MySql connector giving me a new connection when I expected it to give me an open one from the pool. If you have any ideas on that, let me know :)

**Comment by mwillebrands** [comment]
See #7
